### ISSUE TITLE
Race condition while serializing Server.System.ScenarioStoreSystem.CurrentScenarios in BackupScenarios()

### ISSUE THREAD

**Issue by GOAE** [LunaMultiplayer/LunaMultiplayer#509]
Background:

- OS: Windows Server 2022 Standard x64
- KSP Version: 
- LMP version: 0.29.0

---

Mods (remember that **mods are not supported**):  

---

Expected behaviour:  
Backups should execute without a race condition that can cause a crash.

Current behaviour:  
There is a race condition where backups can execute while a concurrent modification of the Server.System.ScenarioStoreSystem.CurrentScenarios dictionary is being made resulting in an exception from a thread pool worker. The underlying cause appears to be a flawed design pattern that does not use a common lock or appropriate compartmentalization. There exists named semaphores to allow similar functions to modify parts of the CurrentScenarios dictionary without a race condition between them. But the issue is that the backup task must read from all data in the dictionary and it does not lock any of those specialized semaphores, hence those separate locks fail to protect the dictionary. The backup lock object also fails to protect the dictionary as it is not locked by the functions that lock with semaphores. This problem is likely exacerbated when writing to slower media or when using a slower processor, but regardless of the media or processor there is a chance the crash will occur.

---

Steps to reproduce:  
Inconsistently reproduced. Probably can only be easily encountered if the backup task is intentionally slowed down considerably. But the issue likely only occurs while a client is connected while the backup task is executed. The more clients the more likely the race condition is encountered, but I have encountered the crash with only one client connected.

Here is the exception:
```
Unhandled exception. System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at LunaConfigNode.CfgNodeWriter.WriteNodes(IEnumerable`1 nodes, StringBuilder builder)
   at LunaConfigNode.CfgNodeWriter.WriteConfigNode(ConfigNode node)
   at LunaConfigNode.CfgNodeWriter.WriteNodes(IEnumerable`1 nodes, StringBuilder builder)
   at LunaConfigNode.CfgNodeWriter.WriteConfigNode(ConfigNode node)
   at LunaConfigNode.CfgNode.ConfigNode.ToString()
   at Server.System.ScenarioStoreSystem.BackupScenarios() in C:\projects\lunamultiplayer\Server\System\ScenarioStoreSystem.cs:line 80
   at Server.System.BackupSystem.RunBackup() in C:\projects\lunamultiplayer\Server\System\BackupSystem.cs:line 45
   at Server.System.BackupSystem.PerformBackups(CancellationToken token) in C:\projects\lunamultiplayer\Server\System\BackupSystem.cs:line 23
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by AndyClausen** [comment]
My friend and I just started getting this pretty consistently on 0.29.2. It's pretty ironic that a backup system is causing us to lose progress lol. Could a hotfix be to copy the collection before enumerating?

**Comment by ShiralynDev** [comment]
> My friend and I just started getting this pretty consistently on 0.29.2. It's pretty ironic that a backup system is causing us to lose progress lol. Could a hotfix be to copy the collection before enumerating?

A long-term backup system is in progress which would atleast mitigate the issue by having data to go back to. I will send this directly to dev team to discuss since it seems to be a pretty large and urgent issue.

**Comment by BraveCaperCat2** [comment]
> My friend and I just started getting this pretty consistently on 0.29.2. It's pretty ironic that a backup system is causing us to lose progress lol. Could a hotfix be to copy the collection before enumerating?

The `0.29.2` version doesn't have a backup system - the one currently in place really just saves your game to disk.

**Comment by ShiralynDev** [comment]
> > My friend and I just started getting this pretty consistently on 0.29.2. It's pretty ironic that a backup system is causing us to lose progress lol. Could a hotfix be to copy the collection before enumerating?
> 
> The `0.29.2` version doesn't have a backup system - the one currently in place really just saves your game to disk.

The save system is called backup system.

**Comment by BraveCaperCat2** [comment]
> > > My friend and I just started getting this pretty consistently on 0.29.2. It's pretty ironic that a backup system is causing us to lose progress lol. Could a hotfix be to copy the collection before enumerating?
> > 
> > 
> > The `0.29.2` version doesn't have a backup system - the one currently in place really just saves your game to disk.
> 
> The save system is called backup system.

Yeah, but it doesn't actually save backups (hence why I said "a backup system" rather than "the backup system")
