### ISSUE TITLE
Server window closes rapidly (.NET 5 installed)

### ISSUE THREAD

**Issue by AlwaysDani1** [LunaMultiplayer/LunaMultiplayer#528]
Hello, I am trying to open the server but the windows closes really quickly after launch. Me and my friend is able to join the server, but after that it quickly disconnects.
I am NOT using VPN or any Hamachi programs, just UPnP default port.
YES, I have installed .NET 5 runtime and I dont have any other .NET runtimes on my PC.

Background:

- OS: Windows 11 21H2
- KSP Version: 1.12 (the newest version)
- LMP version: 0.29.0

Expected behaviour:  
Server start

Current behaviour:  
Server crashes
---
Steps to reproduce:
Start the server. After that the server dies.

**Comment by Fierce-Cat** [comment]
Do you have your .NET 5 runtime installed? Check this guide for more detail: https://github.com/LunaMultiplayer/LunaMultiplayer/wiki/Create-a-server

**Comment by DasSkelett** [comment]
Are you familiar with the console/command prompt on Windows?
Please open a command prompt (e.g. enter "CMD" into start menu search), go into the LMPServer directory (use the "cd" command to move around, you are starting in your user directory. E.g. `cd Downloads` to go into you Downloads folder, or `cd ..` to go one folder up), then enter `Server.exe` to start it from inside the prompt.
Now the window should stay open for you to read any potential error message.

**Comment by AlwaysDani1** [comment]
C:\Users\danie\Desktop\LMPServer>Server.exe
[11:01:31][Info]: Remember! Quit the server by using 'Control + C' so a backup is properly made before closing!
[11:01:31][LMP]: Luna Server version: 0.29.0 (C:\Users\danie\Desktop\LMPServer\)
[11:01:31][Debug]: Loading universe... 0KB
[11:01:31][Debug]: Loading groups...
[11:01:31][Debug]: Loading settings...
[11:01:31][Debug]: Loading mod control...
[11:01:31][Debug]: Loading plugins...
[11:01:31][Debug]: Creating new subspace file
[11:01:31][Debug]: Creating new start time file
[11:01:31][LMP]: Starting 'DaniServer' on Address 0.0.0.0 Port 8800...
[11:01:32][Debug]: UPnP active. Port: 8800 Udp opened!
[11:01:32][Debug]: UPnP + Website active. Port: 8900 Tcp opened!
[11:01:32][LMP]: All systems up and running. Поехали!
[11:01:32][LMP]: Registering with master servers
[11:01:32][Debug]: Performing a GarbageCollection
[11:01:38][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10065): A contact operation was attempted to a host that cannot be reached.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 289
[11:01:38][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10065): A contact operation was attempted to a host that cannot be reached.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 289
[11:01:38][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10065): A contact operation was attempted to a host that cannot be reached.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 289
[11:01:38][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10065): A contact operation was attempted to a host that cannot be reached.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 289
[11:01:38][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10065): A contact operation was attempted to a host that cannot be reached.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 289
[11:01:38][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10065): A contact operation was attempted to a host that cannot be reached.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 289
[11:01:38][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10065): A contact operation was attempted to a host that cannot be reached.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 289
[11:01:38][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10065): A contact operation was attempted to a host that cannot be reached.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 289
[11:01:38][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10065): A contact operation was attempted to a host that cannot be reached.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 289
[11:01:38][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10065): A contact operation was attempted to a host that cannot be reached.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 289
[11:01:38][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10065): A contact operation was attempted to a host that cannot be reached.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 289
[11:01:38][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10065): A contact operation was attempted to a host that cannot be reached.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 289
[11:01:48][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10065): A contact operation was attempted to a host that cannot be reached.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 289
[11:01:48][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10065): A contact operation was attempted to a host that cannot be reached.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 289
[11:01:48][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10065): A contact operation was attempted to a host that cannot be reached.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 289
[11:01:48][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10065): A contact operation was attempted to a host that cannot be reached.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 289
[11:01:48][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10065): A contact operation was attempted to a host that cannot be reached.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 289
[11:01:48][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10065): A contact operation was attempted to a host that cannot be reached.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 289
[11:01:48][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10065): A contact operation was attempted to a host that cannot be reached.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 289
[11:01:48][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10065): A contact operation was attempted to a host that cannot be reached.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 289
[11:01:48][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10065): A contact operation was attempted to a host that cannot be reached.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 289
[11:01:48][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10065): A contact operation was attempted to a host that cannot be reached.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 289
[11:01:48][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10065): A contact operation was attempted to a host that cannot be reached.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 289
[11:01:48][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10065): A contact operation was attempted to a host that cannot be reached.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 289

**Comment by AlwaysDani1** [comment]
**Another error that came up before Server.exe closed.**

Unhandled exception. System.UnauthorizedAccessException: Access to the path 'C:\Users\danie\Desktop\LMPServer\Universe\Subspace.txt' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Server.System.FileHandler.WriteToFile(String path, Byte[] data, Int32 numBytes) in C:\projects\lunamultiplayer\Server\System\FileHandler.cs:line 61
   at Server.System.FileHandler.WriteToFile(String path, String text) in C:\projects\lunamultiplayer\Server\System\FileHandler.cs:line 76
   at Server.System.WarpSystem.BackupSubspaces() in C:\projects\lunamultiplayer\Server\System\WarpSystem.cs:line 31
   at Server.System.BackupSystem.RunBackup() in C:\projects\lunamultiplayer\Server\System\BackupSystem.cs:line 43
   at Server.System.BackupSystem.PerformBackups(CancellationToken token) in C:\projects\lunamultiplayer\Server\System\BackupSystem.cs:line 23
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by AlwaysDani1** [comment]
I turned off backup, now it says this.

Unhandled exception. System.UnauthorizedAccessException: Access to the path 'C:\Users\danie\Desktop\LMPServer\Universe\Subspace.txt' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Server.System.FileHandler.WriteToFile(String path, Byte[] data, Int32 numBytes) in C:\projects\lunamultiplayer\Server\System\FileHandler.cs:line 61
   at Server.System.FileHandler.WriteToFile(String path, String text) in C:\projects\lunamultiplayer\Server\System\FileHandler.cs:line 76
   at Server.System.WarpSystem.BackupSubspaces() in C:\projects\lunamultiplayer\Server\System\WarpSystem.cs:line 31
   at Server.System.BackupSystem.RunBackup() in C:\projects\lunamultiplayer\Server\System\BackupSystem.cs:line 43
   at Server.System.BackupSystem.PerformBackups(CancellationToken token) in C:\projects\lunamultiplayer\Server\System\BackupSystem.cs:line 23
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by DasSkelett** [comment]
> ```
> [Debug] Performing backups...
> Unhandled exception. System.UnauthorizedAccessException: Access to the path 'C:\Users\danie\Desktop\LMPServer\Universe\Subspace.txt' is denied.
> ```

It looks like this one is the one that causes the server to stop.
For some reason the server is not allowed to create or overwrite this file in its own folder.
Did you run it as administrator before? Then it might have created this file with elevated privileges.

Try to delete this file, or better the entire `Universe` folder, then run the server again. But don't run it as admin, it isn't required and messes up permissions as you can see.

**Comment by AlwaysDani1** [comment]
I deleted the Universe folder and ran the server again in cmd with no elevated access. still same error.

**Comment by DasSkelett** [comment]
Then please try deletin the entire `LMPServer` folder and redownloadong the zip and extracting it.

While the Desktop should usually work, maybe try placing it in a different directory as well, e.g. directly in your user folder.

**Comment by AlwaysDani1** [comment]
This fixed it, thanks.
