### ISSUE TITLE
Server crashes with "Access to Subspace.txt is denied"

### ISSUE THREAD

**Issue by 9zq** [LunaMultiplayer/LunaMultiplayer#531]
Background:

- OS: Windows 10
- KSP Version: 1.12.4
- LMP version (include the build number if you are using a nighly build): 0.29

---

Mods (remember that **mods are not supported**):  
None

---

Expected behaviour:  
Server does not crash.

Current behaviour:  
Server runs normal but after a short while in game crashes with the error message: 
[20:43:59][Debug]: Performing backups...
[20:43:59][Fatal]: ERROR in thread receive! Details: System.UnauthorizedAccessException: Access to the path 'C:\path\to\server\LMPServer\Universe\Subspace.txt' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Server.System.FileHandler.WriteToFile(String path, Byte[] data, Int32 numBytes) in C:\projects\lunamultiplayer\Server\System\FileHandler.cs:line 61
   at Server.System.FileHandler.WriteToFile(String path, String text) in C:\projects\lunamultiplayer\Server\System\FileHandler.cs:line 76
   at Server.System.WarpSystem.BackupSubspaces() in C:\projects\lunamultiplayer\Server\System\WarpSystem.cs:line 31
   at Server.System.BackupSystem.RunBackup() in C:\projects\lunamultiplayer\Server\System\BackupSystem.cs:line 43
   at Server.Client.ClientConnectionHandler.DisconnectClient(ClientStructure client, String reason) in C:\projects\lunamultiplayer\Server\Client\ClientConnectionHandler.cs:line 65
   at Server.Server.LidgrenServer.StartReceivingMessages() in C:\projects\lunamultiplayer\Server\Server\LidgrenServer.cs:line 131

I thought it was mods originally but i removed them all and it still does this. Launching with admin perms changes nothing. No "Subspace.txt" file exists in that spot.

Attached log does not have error message for some reason. 
---

Steps to reproduce:  
Join server. Try to build something. Wait for "Performing backups" message to appear. Server crashes.

[lmpserver_2023-01-09_16-17-52.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/10376928/lmpserver_2023-01-09_16-17-52.log)

**Comment by 9zq** [comment]
Antivirus was blocking it for some reason.
