### ISSUE TITLE
I need help 

### ISSUE THREAD

**Issue by jofra296** [LunaMultiplayer/LunaMultiplayer#535]
my server repeatedly pops up with this code over and over again. when I try to join the server I do so just fine but when my friends try it says failed to connect if someone know how to fix this please help

EP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 319
[22:54:55][Debug]: Lidgren: ERRORMESSAGE -- Failed to send packet: System.Net.Sockets.SocketException (10051): A socket operation was attempted to an unreachable network.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset) in C:\projects\lunamultiplayer\Lidgren\NetPeer.LatencySimulation.cs:line 319

**Comment by DasSkelett** [comment]
You've most likely misconfigured the `ListenAddress`. Keep it at the default, the default is the default for a reason.

**Comment by Sarrrib** [comment]
After starting the server.exe, the command line appears for a second and asks what to do, please help
