### ISSUE TITLE
Share Craft Folder Structure

### ISSUE THREAD

**Issue by mrben1985** [LunaMultiplayer/LunaMultiplayer#59]
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in ".\Kerbal Space Program\KSP_x64_Data\output_log.txt"

------------------------------------------------------------------------------

OS: Windows 10

------------------------------------------------------------------------------

KSPVersion: 

------------------------------------------------------------------------------

MODS (add link to download them): None

------------------------------------------------------------------------------

Expected behaviour: Multiplayer game loads correctly.

------------------------------------------------------------------------------

Current behaviour: Multiplayer game wont start when a player uploads a ship for sharing. As it is trying to sync folders that do not exist. 

[20:04:27][Info] : Client MrBen handshook successfully, Version: 0.0.9
[20:04:27][Debug] : Online Players: 2, connected: 2
[20:04:28][Debug] : Sending MrBen 4 kerbals...
[20:04:29][Debug] : Sending MrBen 1 possible subspaces
[20:04:30][Fatal] : ERROR in thread receive! Details: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\servers\ksp\LMPServer\Universe\Crafts\HybridGorilla\SPH'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at Server.System.FileHandler.GetFilesInPath(String path, SearchOption searchOption)
   at Server.Message.ReceiveHandlers.CraftLibraryHandler.SendCraftList(ClientStructure client)
   at Server.Message.Reader.CraftLibraryMsgReader.HandleMessage(ClientStructure client, IMessageData message)
   at Server.Server.MessageReceiver.ReceiveCallback(ClientStructure client, NetIncomingMessage msg)
   at Server.Lidgren.LidgrenServer.<StartReceiveingMessages>d__14.MoveNext()

------------------------------------------------------------------------------

Steps to reproduce:  Share a craft and then try to reconnect to the server.

**Comment by gavazquez** [comment]
Fixed in commit [ef2f409](https://github.com/LunaMultiplayer/LunaMultiplayer/commit/ef2f4096d8cf1282421f175102100badee495b65)

It should be fixed since the automatic appveyor build 0.0.9.376
